apiVersion: v1
kind: Secret
metadata:
  name: green-trade-secrets
  namespace: green-trade
type: Opaque
stringData:
  DATABASE_URL: "mongodb://green-trade-mongo:27017/greentrade?replicaSet=rs0&directConnection=true" # Modifiez si nécessaire
  JWT_SECRET: "PLACEHOLDER_JWT_SECRET"
  CLOUDINARY_CLOUD_NAME: "PLACEHOLDER_CLOUDINARY_CLOUD_NAME"
  CLOUDINARY_API_KEY: "PLACEHOLDER_CLOUDINARY_API_KEY"
  CLOUDINARY_API_SECRET: "PLACEHOLDER_CLOUDINARY_API_SECRET"
  EMAIL_USER: "PLACEHOLDER_EMAIL_USER"
  EMAIL_PASSWORD: "PLACEHOLDER_EMAIL_PASSWORD"
  EMAIL_FROM: "PLACEHOLDER_EMAIL_FROM"
  STRIPE_SECRET_KEY: "PLACEHOLDER_STRIPE_SECRET_KEY"
  STRIPE_WEBHOOK_SECRET: "PLACEHOLDER_STRIPE_WEBHOOK_SECRET"