apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: green-trade-catalog-api-hpa
  namespace: green-trade
  labels:
    app.kubernetes.io/name: green-trade
    app.kubernetes.io/component: catalog-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: green-trade-catalog-api
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
